In [1]:
import numpy as np

In [2]:
import array 
#array package is also available by default in python, but it lacks a lot of functions that are required in numpy array
# as we prooceed later, we will realize that every kind of data is available either in array or matrices

In [3]:
np.array([2134,3245,456,234,2353,6])

array([2134, 3245,  456,  234, 2353,    6])

In [4]:
a = np.array([2134,3245,456,234,2353,6])

In [5]:
type(a) #nd = n-dimensional

numpy.ndarray

In [6]:
a = np.array([2134,3245,456,234,2353,6,"sdfgdfg", 4+8j ])

In [7]:
a #dtype='<U64' ------ everything in computer is divided into bits and bytes...numpy gives us a flexibility to convert 64 to 32...32 to 8 etc

array(['2134', '3245', '456', '234', '2353', '6', 'sdfgdfg', '(4+8j)'],
      dtype='<U64')

In [8]:
a = np.array([2134,3245,456,234,2353,6.235345324])

In [9]:
a # all the integers are being upcasted as floating point numbers

array([2134.        , 3245.        ,  456.        ,  234.        ,
       2353.        ,    6.23534532])

In [11]:
np.array([[234,345],[213423,345]])

array([[   234,    345],
       [213423,    345]])

In [12]:
np.array([[234,345],[213423,345], [234,56]])

array([[   234,    345],
       [213423,    345],
       [   234,     56]])

In [13]:
np.array([[234,345],[213423,345], [234,56, 2345]])

#its giving deprecated warning,,,that dimension of array is not usual,,,number of elements inside sub-arrays is not same in all case
#it gives array but it is giving a list of array

C:\Users\Utkarsh\AppData\Local\Temp/ipykernel_7944/1098267338.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[234,345],[213423,345], [234,56, 2345]])


array([list([234, 345]), list([213423, 345]), list([234, 56, 2345])],
      dtype=object)

In [14]:
np.array([[[234,345],[213423,345]]]) #3-d array ,,,bcoz of 3 brackets in the beginning and the end

array([[[   234,    345],
        [213423,    345]]])

In [15]:
np.array([123,2345,345], ndmin =3)
#ndmin gives us flexibilty to define dimension of the array

array([[[ 123, 2345,  345]]])

In [16]:
np.array([123,2345,345], dtype = complex)
#typecasting,,,,or defining data-type

array([ 123.+0.j, 2345.+0.j,  345.+0.j])

In [17]:
np.array([(1,2),(4,5)]) 
#it does not matter whether elements of an array are in list or in tuple, we will be able to get the same data in both the cases

array([[1, 2],
       [4, 5]])

In [18]:
#if we want to define different data types to different elements, we can follow data type mapping

arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [19]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [20]:
arr[0]

(1, 2)

In [21]:
arr[0][0]

1

In [22]:
type(arr[0][0])

numpy.int32

In [23]:
arr[0][1]

2

In [24]:
type(arr[0][1])

numpy.int64

In [25]:
type(arr[1][0])

numpy.int32

In [26]:
type(arr[1][1])

numpy.int64

In this way, we can save memory

#i2 = 16 bit
#i4 = 32 bit
#i8 = 64 bit

In [27]:
arr = np.array([(1,3) , (3,4)])

In [28]:
arr[0][0] #follow row, columns convention

1

In [29]:
arr[0][1]

3

In [30]:
arr[1][0]

3

In [31]:
arr[1][1]

4

In [32]:
#converting array to matrix
#matrix is a subset of array

np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [33]:
np.matrix(arr)

matrix([[1, 3],
        [3, 4]])

In [34]:
l = [234,456,6,34,2343]

In [35]:
np.array(l)

array([ 234,  456,    6,   34, 2343])

In [36]:
np.asarray(l)

array([ 234,  456,    6,   34, 2343])

In [37]:
np.asanyarray(l)

#asanyarray will not be able to convert matrix into array as list is not a type of array

array([ 234,  456,    6,   34, 2343])

In [38]:
mat = np.matrix(arr)

In [39]:
np.asanyarray(mat)

#asanyarray will not be able to convert matrix into array as matrix itself is a type of array

matrix([[1, 3],
        [3, 4]])

In [40]:
np.asarray(mat)

#asarray will be able to convert anything into array

array([[1, 3],
       [3, 4]])

In [41]:
#checking whether a given thing is a subclass of another or not

issubclass(np.matrix,np.ndarray)

# here we are checking if matrix is a subclass of array or not

True

In [42]:
issubclass(np.ndarray, np.matrix)

False

### deep copy and shallow copy

In [43]:
a = arr

In [44]:
b = np.copy(arr)

In [45]:
#assigning different value:
arr[0][0] = 34
# array elements are mutable

In [46]:
a 

# it is holding the changed data
# it is refering to the same location
# it is shallow copy

array([[34,  3],
       [ 3,  4]])

In [47]:
b 

# it is holding the original data
# it is creating a new reference, due to which we are unable to see any change
# it is deep copy

array([[1, 3],
       [3, 4]])

In [48]:
arr[0:10] #slicing and indexing operations can also be applied here

array([[34,  3],
       [ 3,  4]])

In [49]:
for i in arr:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


###  some more functions

In [51]:
np.fromfunction(lambda i,j: i == j, (4,4)) 
# 4 into 4 is the size of the array

#fromfunction helps you out to generate nd array depending on the logic we are going to provide

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [52]:
type(np.fromfunction(lambda i,j: i == j, (4,4)) 
)

numpy.ndarray

In [53]:
np.fromfunction(lambda i,j: i * j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
np.fromfunction(lambda i,j: i ** j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [55]:
np.fromfunction(lambda i,j: i / j, (3,3))

#infinity is a keyword that exists in numpy...that is why we are not getting any error even if divided by zero

C:\Users\Utkarsh\AppData\Local\Temp/ipykernel_7944/607527384.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j: i / j, (3,3))
C:\Users\Utkarsh\AppData\Local\Temp/ipykernel_7944/607527384.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j: i / j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [56]:
1234/0

ZeroDivisionError: division by zero

In [57]:
[i*i for i in range(5)] #list comprehension

[0, 1, 4, 9, 16]

In [58]:
(i*i for i in range(5)) #generator object

<generator object <genexpr> at 0x000001EE067FF5F0>

In [59]:
#in this way, we can also create generator object
def test(x):
    yield x
    
test(234234)

<generator object test at 0x000001EE066E32E0>

In [60]:
gen = (i*i for i in range(5)) #generator object

In [61]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [62]:
np.fromiter(range(34), dtype = int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [63]:
np.fromstring("1234,345,3456,56,7,234", sep = ",", dtype = int)

array([1234,  345, 3456,   56,    7,  234])

In [64]:
np.fromstring("2345456 4567 678 345 45 6324", sep = " ", dtype = complex)

array([2.345456e+06+0.j, 4.567000e+03+0.j, 6.780000e+02+0.j,
       3.450000e+02+0.j, 4.500000e+01+0.j, 6.324000e+03+0.j])

In [65]:
l =[2354345,345,456,3456,467]

In [66]:
np.array(l)

array([2354345,     345,     456,    3456,     467])

In [67]:
arr = np.array(l)

In [69]:
arr1 = np.array([[234,345,234,3245],[2342345,2354,34,123],[587, 342534,33,45]])

In [70]:
arr1.ndim

2

In [71]:
arr1.size

12

In [72]:
arr1.shape #3 rows, 4 columns

(3, 4)

In [73]:
arr1.dtype

dtype('int32')

In [74]:
arr.size

5

In [75]:
arr.ndim

1

In [76]:
arr.shape

(5,)

In [90]:
arr2 = np.array([[[2342345,345,345,234], [2343456,456,56721341,2345]],[[12342345,2345,34,235],[2354345,356,567,3565]]])

In [91]:
arr2

array([[[ 2342345,      345,      345,      234],
        [ 2343456,      456, 56721341,     2345]],

       [[12342345,     2345,       34,      235],
        [ 2354345,      356,      567,     3565]]])

In [92]:
arr2.size

16

In [93]:
arr2.shape # we have 2 no of 2*4 data

(2, 2, 4)

In [94]:
arr2.ndim

3

In [95]:
arr3 = np.array([[[[2342345,345,345,234], [2343456,456,56721341,2345]],[[12342345,2345,34,235],[2354345,356,567,3565]]]])

In [96]:
arr3.ndim

4

In [97]:
arr3.shape

(1, 2, 2, 4)

In [99]:
range(5)

range(0, 5)

In [100]:
[range(6)]

[range(0, 6)]

In [102]:
[range(6.6)] #range fn always takes integers

# we cant define jump
# it does not accept upperbound

TypeError: 'float' object cannot be interpreted as an integer

In [103]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [104]:
np.arange(6.6, 9, 0.3)

#arange fn includes upperbound if dtype is not integer 

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [108]:
np.arange(9,6.6, -.3)

#arange fn doesn't include upperbound if dtype is integer

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [109]:
np.arange(1,9)



array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
np.linspace(3,9,5) 

#generating particular number of data with equal intervals between two given boundaries

array([3. , 4.5, 6. , 7.5, 9. ])

In [112]:
np.linspace(3,9) #by default, number of data is = 50

array([3.        , 3.12244898, 3.24489796, 3.36734694, 3.48979592,
       3.6122449 , 3.73469388, 3.85714286, 3.97959184, 4.10204082,
       4.2244898 , 4.34693878, 4.46938776, 4.59183673, 4.71428571,
       4.83673469, 4.95918367, 5.08163265, 5.20408163, 5.32653061,
       5.44897959, 5.57142857, 5.69387755, 5.81632653, 5.93877551,
       6.06122449, 6.18367347, 6.30612245, 6.42857143, 6.55102041,
       6.67346939, 6.79591837, 6.91836735, 7.04081633, 7.16326531,
       7.28571429, 7.40816327, 7.53061224, 7.65306122, 7.7755102 ,
       7.89795918, 8.02040816, 8.14285714, 8.26530612, 8.3877551 ,
       8.51020408, 8.63265306, 8.75510204, 8.87755102, 9.        ])

In [113]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.zeros((7,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.zeros((2,7,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [117]:
np.ones(4) # only ones zeros are available in numpy

array([1., 1., 1., 1.])

In [118]:
np.empty(5) #random data

array([3. , 4.5, 6. , 7.5, 9. ])

In [119]:
np.empty((3,4))

array([[1.04829175e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.06811354e-306, 3.50532773e-033, 1.68914820e-051,
        1.41919973e+161],
       [2.44306760e-052, 4.25990244e+174, 2.74324223e-057,
        1.17665270e-047]])

In [120]:
np.eye(3) # 3 means 3*3 bcoz identity matrix is always a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
np.linspace(2,4,4,endpoint=True)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [122]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [123]:
np.linspace(2,4,4) #by default, it is true

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [124]:
np.linspace(2,4,4,endpoint=False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [125]:
np.linspace(2,4,4,endpoint=False, axis = 1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [126]:
np.linspace(np.array([1,2]),np.array([3,4]),4,endpoint=False, axis = 0)

array([[1. , 2. ],
       [1.5, 2.5],
       [2. , 3. ],
       [2.5, 3.5]])

In [127]:
np.linspace(np.array([1,2]),np.array([3,4]),4,endpoint=False, axis = 1)

array([[1. , 1.5, 2. , 2.5],
       [2. , 2.5, 3. , 3.5]])

In [128]:
np.linspace(np.array([1,2]),np.array([3,4]),4,endpoint=False, axis = 2)

AxisError: destination: axis 2 is out of bounds for array of dimension 2

In [130]:
np.linspace([1,6],4,endpoint=False, axis = 1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [131]:
np.linspace([1,6],4,endpoint=False, axis = 0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [132]:
np.logspace(2,3,5) 
#5 logarithimic of data b/w 2 and 3
#default is base 10

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [133]:
np.logspace([2,3],5) 


array([[   100.        ,   1000.        ],
       [   115.13953993,   1098.54114199],
       [   132.57113656,   1206.79264064],
       [   152.64179672,   1325.71136559],
       [   175.75106249,   1456.3484775 ],
       [   202.35896477,   1599.85871961],
       [   232.99518105,   1757.51062485],
       [   268.26957953,   1930.69772888],
       [   308.88435965,   2120.95088792],
       [   355.64803062,   2329.95181052],
       [   409.49150624,   2559.5479227 ],
       [   471.48663635,   2811.76869797],
       [   542.86754393,   3088.84359648],
       [   625.05519253,   3393.2217719 ],
       [   719.685673  ,   3727.59372031],
       [   828.64277285,   4094.91506238],
       [   954.09547635,   4498.43266897],
       [  1098.54114199,   4941.71336132],
       [  1264.85521686,   5428.67543932],
       [  1456.3484775 ,   5963.62331659],
       [  1676.83293681,   6551.2855686 ],
       [  1930.69772888,   7196.85673001],
       [  2222.99648253,   7906.04321091],
       [  2

In [134]:
np.logspace([2,3],5, axis = 1)

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [135]:
np.logspace([2],[3], axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [136]:
np.logspace([2],[3], axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [137]:
d = np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [138]:
d.ndim

1

In [139]:
d.shape

(40,)

In [141]:
#arranginging the data,d in different dimensions and shapes
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [143]:
d.reshape(2, 2, 10) #ensure that 2*2*10 must be equal to d

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [144]:
d.reshape(5, 2, 4)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923],
        [4.30769231, 4.38461538, 4.46153846, 4.53846154]],

       [[4.61538462, 4.69230769, 4.76923077, 4.84615385],
        [4.92307692, 5.        , 5.07692308, 5.15384615]],

       [[5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077]],

       [[5.84615385, 5.92307692, 6.        , 6.07692308],
        [6.15384615, 6.23076923, 6.30769231, 6.38461538]],

       [[6.46153846, 6.53846154, 6.61538462, 6.69230769],
        [6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [145]:
d.reshape(5, 2, 5)

ValueError: cannot reshape array of size 40 into shape (5,2,5)

In [146]:
d.reshape(2, 2, 5, 2)

array([[[[4.        , 4.07692308],
         [4.15384615, 4.23076923],
         [4.30769231, 4.38461538],
         [4.46153846, 4.53846154],
         [4.61538462, 4.69230769]],

        [[4.76923077, 4.84615385],
         [4.92307692, 5.        ],
         [5.07692308, 5.15384615],
         [5.23076923, 5.30769231],
         [5.38461538, 5.46153846]]],


       [[[5.53846154, 5.61538462],
         [5.69230769, 5.76923077],
         [5.84615385, 5.92307692],
         [6.        , 6.07692308],
         [6.15384615, 6.23076923]],

        [[6.30769231, 6.38461538],
         [6.46153846, 6.53846154],
         [6.61538462, 6.69230769],
         [6.76923077, 6.84615385],
         [6.92307692, 7.        ]]]])

In [147]:
np.random.rand(3) #normal distribution

array([0.92867555, 0.14004863, 0.41158546])

In [149]:
np.random.randn(3) #standard normal distribution i.e. mean = 0 and std devn = 1

array([-0.14530715, -1.21022636, -1.17989838])

In [150]:
np.random.randn(5,4)

array([[ 0.55533804,  1.40728833, -0.05770847, -0.33015868],
       [-1.4350997 , -0.26329857, -0.82612751, -1.19009569],
       [-0.46176787,  0.19104165,  0.46610806, -0.24644034],
       [-2.03510806, -0.3921997 ,  1.07442236,  0.63128568],
       [-0.6918515 ,  1.78458971,  1.88691615,  1.95567321]])

In [151]:
np.random.randn(5,4,2)

array([[[ 1.29484705, -0.21861185],
        [-0.62008894, -1.31029641],
        [-1.45165589,  0.6163667 ],
        [ 0.27946548, -1.71810001]],

       [[-0.56003621,  1.45951015],
        [ 1.57713299,  1.24330921],
        [ 0.29397643, -0.30777015],
        [ 0.48081407,  0.56489221]],

       [[-1.03790935, -0.69237808],
        [ 0.42839017, -0.13230722],
        [-0.68760364,  0.42202949],
        [ 0.97222145, -0.05735114]],

       [[-0.42233337,  1.24205308],
        [ 0.36521711, -0.00385021],
        [-0.93912886,  0.8231937 ],
        [ 0.06065472, -0.94510382]],

       [[-0.59924298,  1.00954369],
        [ 0.98309942, -1.60944482],
        [-0.62809544,  2.68593272],
        [ 0.52700554,  1.81460633]]])

In [152]:
np.random.randint(5, 60, size = 3)

array([51,  6,  8])

In [153]:
np.random.randint(5, 60, size = 3)

array([34, 14, 12])

In [154]:
np.random.randint(5, 60, size = 3)

array([52, 49,  8])

In [155]:
np.random.randint(5, 60, (4,7))

array([[40, 16, 50, 42, 32, 23, 31],
       [27, 23, 54, 55, 14, 58, 19],
       [36, 59, 54, 24, 50, 36, 47],
       [ 6, 46, 32, 37, 28, 56, 56]])

In [157]:
arr = np.random.randint(3,9,(3,3))

In [158]:
arr

array([[7, 3, 6],
       [6, 8, 5],
       [7, 6, 5]])

In [159]:
arr.reshape(1,9)

array([[7, 3, 6, 6, 8, 5, 7, 6, 5]])

In [160]:
arr.reshape(9,1)

array([[7],
       [3],
       [6],
       [6],
       [8],
       [5],
       [7],
       [6],
       [5]])

In [161]:
arr.reshape(3, 3,1)

array([[[7],
        [3],
        [6]],

       [[6],
        [8],
        [5]],

       [[7],
        [6],
        [5]]])

In [162]:
arr.reshape(3,-1)

array([[7, 3, 6],
       [6, 8, 5],
       [7, 6, 5]])

In [163]:
arr.reshape(3,-1364654645) #by giving negative number, it is able to understand itself the dim of the matrix

array([[7, 3, 6],
       [6, 8, 5],
       [7, 6, 5]])

In [164]:
arr.max

<function ndarray.max>

In [165]:
arr.max()

8

In [166]:
arr.min()

3

In [167]:
arr.ndim

2

In [168]:
arr = np.random.randint(4,100,(5,5))
arr

array([[33, 27, 10, 38, 64],
       [20, 13, 29, 19, 66],
       [61, 91, 66, 42, 41],
       [45, 37,  9, 62, 67],
       [72, 46, 34, 25, 31]])

In [169]:
arr[3:,3:]

array([[62, 67],
       [25, 31]])

In [171]:
arr[0:, [1,3]] # , se pahle rows and , k baad columns

array([[27, 38],
       [13, 19],
       [91, 42],
       [37, 62],
       [46, 25]])

In [173]:
arr[0:2, [1,3]]

array([[27, 38],
       [13, 19]])

In [174]:
arr>10

array([[ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [175]:
arr[arr>10] #giving array of elements > 10

array([33, 27, 38, 64, 20, 13, 29, 19, 66, 61, 91, 66, 42, 41, 45, 37, 62,
       67, 72, 46, 34, 25, 31])

In [179]:
arr[arr>10][::-1]

array([31, 25, 34, 46, 72, 67, 62, 37, 45, 41, 42, 66, 91, 61, 66, 19, 29,
       13, 20, 64, 38, 27, 33])

In [180]:
arr

array([[33, 27, 10, 38, 64],
       [20, 13, 29, 19, 66],
       [61, 91, 66, 42, 41],
       [45, 37,  9, 62, 67],
       [72, 46, 34, 25, 31]])

In [181]:
arr*arr

array([[1089,  729,  100, 1444, 4096],
       [ 400,  169,  841,  361, 4356],
       [3721, 8281, 4356, 1764, 1681],
       [2025, 1369,   81, 3844, 4489],
       [5184, 2116, 1156,  625,  961]])

In [182]:
arr1 = np.random.randint(2,4,(3,3))

In [183]:
arr2 = np.random.randint(2,4,(3,3))

In [184]:
arr1

array([[3, 3, 2],
       [3, 2, 3],
       [2, 3, 3]])

In [185]:
arr2

array([[2, 3, 2],
       [2, 3, 2],
       [2, 2, 3]])

In [186]:
arr1*arr2 #its not matrix multiplication....its element to element multiplication i.e. index multiplication

array([[6, 9, 4],
       [6, 6, 6],
       [4, 6, 9]])

In [187]:
arr1 = np.random.randint(2,4,(3,3))

In [188]:
arr2 = np.random.randint(2,4,(3,2))

In [189]:
arr1*arr2 # for index wise multiplication, it fails

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [190]:
arr1@arr2 #matrix multiplication i.e a*b and b*c

array([[19, 19],
       [21, 21],
       [19, 19]])

In [191]:
arr1 = np.random.randint(2,4,(3,3))

In [192]:
arr2 = np.random.randint(2,4,(3,3))

In [193]:
arr1@arr2

array([[16, 16, 16],
       [16, 16, 16],
       [16, 16, 16]])

In [194]:
arr/0

C:\Users\Utkarsh\AppData\Local\Temp/ipykernel_7944/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [195]:
arr**2 #element wise opern

array([[1089,  729,  100, 1444, 4096],
       [ 400,  169,  841,  361, 4356],
       [3721, 8281, 4356, 1764, 1681],
       [2025, 1369,   81, 3844, 4489],
       [5184, 2116, 1156,  625,  961]], dtype=int32)

In [196]:
#broadcasting

arr = np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [199]:
#broadcasting

arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [201]:
arr_ = np.array([1,2,3,4])
arr_

array([1, 2, 3, 4])

In [203]:
arr + arr_ #broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [204]:
arr + 5 #broadcasting , row-wise

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [205]:
arr_1 = np.array([1,2,3])

In [206]:
arr_1

array([1, 2, 3])

In [207]:
arr + arr_1 #error due to shape

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [208]:
#column-wise broadcasting

b = np.array([5,6,7])

In [209]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [210]:
b+arr

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [211]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [212]:
b.T #transpose

array([5, 6, 7])

In [213]:
(b.T).T

array([5, 6, 7])

In [214]:
b = np.array([[5,6,7]]) #2-d

In [215]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [216]:
arr = np.random.rand(5,4)

In [217]:
arr

array([[0.64329033, 0.40214806, 0.27533421, 0.93735559],
       [0.66887096, 0.98227363, 0.12254049, 0.20498604],
       [0.29372613, 0.84024263, 0.63923069, 0.07192319],
       [0.43310603, 0.95093354, 0.53366063, 0.24925376],
       [0.03817214, 0.86292982, 0.27387149, 0.51657472]])

In [218]:
np.sqrt(arr)

array([[0.80205382, 0.63415145, 0.52472299, 0.96817126],
       [0.81784532, 0.99109718, 0.35005784, 0.45275384],
       [0.54196506, 0.91664749, 0.79951903, 0.26818499],
       [0.65810792, 0.97515821, 0.73052079, 0.4992532 ],
       [0.19537692, 0.92894016, 0.52332733, 0.71873133]])

In [219]:
np.exp(arr)

array([[1.90273121, 1.49503267, 1.31697075, 2.55322072],
       [1.95203216, 2.67052112, 1.13036489, 1.22750793],
       [1.34141648, 2.31692906, 1.89502245, 1.0745728 ],
       [1.54203972, 2.58812466, 1.70516286, 1.28306758],
       [1.03891005, 2.37009449, 1.3150458 , 1.67627609]])

In [220]:
np.log10(arr)

array([[-0.19159297, -0.39561402, -0.56013982, -0.02809563],
       [-0.17465766, -0.00776751, -0.91172037, -0.68827571],
       [-0.53205741, -0.07559529, -0.19434239, -1.14313108],
       [-0.36340577, -0.02184983, -0.27273484, -0.60335829],
       [-1.4182535 , -0.06402452, -0.56245317, -0.28686685]])

In [221]:
arr1= np.random.randint(2,5, (5,5))

In [222]:
arr1

array([[3, 3, 3, 4, 3],
       [2, 4, 4, 3, 4],
       [2, 2, 3, 3, 3],
       [2, 2, 3, 2, 2],
       [3, 4, 4, 2, 3]])

In [223]:
np.log2(arr1)

array([[1.5849625, 1.5849625, 1.5849625, 2.       , 1.5849625],
       [1.       , 2.       , 2.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.5849625, 1.5849625, 1.5849625],
       [1.       , 1.       , 1.5849625, 1.       , 1.       ],
       [1.5849625, 2.       , 2.       , 1.       , 1.5849625]])

In [224]:
np.random.seed(13)

In [225]:
np.random.rand(2,4) #data will change on each execution

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [226]:
np.random.seed(13) #now data will not change on each execution although its random data
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])